#[allow(non_camel_case_types)]
/// Config completely readed from driver (for debug)
pub struct TMC2209_DebugConfig {
    pub microsteps: u32,
    pub interpolation: bool,
    pub blank_time: u32,
    pub hysteresis_end: u32,
    pub hysteresis_start: u32,
    pub en_spreadcycle: bool,
    pub pdn_disable: bool,
    pub pwm_ofs: u8,
    pub pwm_grad: u8,
    pub pwm_freq: u8,
    pub pwm_autoscale: bool,
    pub pwm_autograd: bool,
    pub pwm_reg: u8,
    pub pwm_lim: u8,
    pub freewheel: u8,
    pub internal_rsense: bool,
    pub i_scale_analog: bool,
    pub mstep_reg_select: bool,
    pub multistep_filt: bool,
    pub index_otpw: bool,
    pub index_step: bool,
    pub toff: u32,
    pub vsense: bool,
    pub dedge: bool,
    pub diss2g: bool,
    pub diss2vs: bool,
    pub fclktrim: u8,
    pub ottrim: u8,
    pub shaft: bool,
}
