#[allow(non_camel_case_types)]
/// When apply_config() called values of user config will be
/// saved in this struct in case of succes send
pub struct TMC2209_SavedConfig {
    pub rms_current: u16,
    pub ihold_delay: u8,
    pub microsteps: u32,
    pub interpolation: bool,
    pub blank_time: u32,
    pub hysteresis_end: u32,
    pub hysteresis_start: u32,
    pub tpowerdown: u32,
    pub tpwmthrs: u32,
    pub sgthrs: u32,
    pub tcoolthrs: u32,
    pub en_spreadcycle: bool,
    pub pdn_disable: bool,
    pub pwm_ofs: u8,
    pub pwm_grad: u8,
    pub pwm_freq: u8,
    pub pwm_autoscale: bool,
    pub pwm_autograd: bool,
    pub pwm_reg: u8,
    pub pwm_lim: u8,
    pub freewheel: u8,
    pub internal_rsense: bool,
    pub i_scale_analog: bool,
    pub mstep_reg_select: bool,
    pub multistep_filt: bool,
    pub index_otpw: bool,
    pub index_step: bool,
    pub senddelay: u8,
    pub semin: u16,
    pub seup: u16,
    pub semax: u16,
    pub sedn: u16,
    pub seimin: bool,
    pub toff: u32,
    pub vsense: bool,
    pub dedge: bool,
    pub diss2g: bool,
    pub diss2vs: bool,
    pub fclktrim: u8,
    pub ottrim: u8,
    pub shaft: bool,
}
